language: generic
os: linux
dist: xenial

services:
  - docker

jobs:
    include:
        - name: py2.7-dj1.11
          install: docker build --build-arg PYTHON_VERSION=2.7 --build-arg DJANGO_VERSION=1.11 -t native -f Dockerfile-tmpl .
          script: docker run -it --rm native pytest --cov --cov-report=term-missing
        - name: py3.6-dj1.11
          install: docker build --build-arg PYTHON_VERSION=3.6 --build-arg DJANGO_VERSION=1.11 -t native -f Dockerfile-tmpl .
          script: docker run -it --rm native pytest --cov --cov-report=term-missing
