name: Test suite

on:
  pull_request:
    branches: [ devel ]
  push:
    branches:
      - master
    tags:
      - "[0-9]*.[0-9]*.*[0-9]"

jobs:
  quality-checks:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Code quality checks
        run: |
          docker build --build-arg PYTHON_VERSION=3.6 --build-arg DJANGO_VERSION=1.11 -t native -f Dockerfile-tmpl .
          docker run --rm native sh -c 'pre-commit run --files $(git ls-files transifex* tests*)'

  python2-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Test py2.7-dj1.11
        run: |
          docker build --build-arg PYTHON_VERSION=2.7 --build-arg DJANGO_VERSION=1.11 -t native -f Dockerfile-tmpl .
          docker run -e CODECOV_TOKEN=$CODECOV_TOKEN --rm native sh -c 'pytest --cov --cov-report=term-missing && codecov'
        env:
          CODECOV_TOKEN: ${{secrets.codecov_token}}

  python3-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Test py3.6-dj1.11
        run: |
          docker build --build-arg PYTHON_VERSION=3.6 --build-arg DJANGO_VERSION=1.11 -t native -f Dockerfile-tmpl .
          docker run -e CODECOV_TOKEN=$CODECOV_TOKEN --rm native sh -c 'pytest --cov --cov-report=term-missing && codecov'
        env:
          CODECOV_TOKEN: ${{secrets.codecov_token}}

  publish-pypi:
    needs: [quality-checks, python2-tests, python3-tests]
    if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags')
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.7
        uses: actions/setup-python@v1
        with:
          python-version: 3.7
      - name: Build source tarball
        run: python setup.py sdist
      - name: Publish package
        uses: pypa/gh-action-pypi-publish@master
        with:
          user: __token__
          password: ${{secrets.pypi_api_token}}
